[tools]
helm = "3.16.2"
poetry = "2.1.1"
pre-commit = "3.8.0"
python = "3.12.0"
tilt = "0.33.21"

[env]
_.python.venv = ".venv"

[tasks.install]
description = "Install/upgrade helm chart"
run = "helm upgrade --install --create-namespace -n remove-empty-ns-operator remove-empty-ns-operator ./helm/"

[tasks.uninstall]
description = "Uninstall helm chart"
run = "helm uninstall -n remove-empty-ns-operator remove-empty-ns-operator"

[tasks.test]
description = "Run tests"
run = "python -m unittest tests/tests.py"

[tasks.push]
description = "Push docker image to a registry"
run = "docker buildx --builder all-platform build --platform linux/amd64,linux/arm64 . -t rgeraskin/remove-empty-ns-operator:1.1.1 --push"
