apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    application: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        settingsHash: {{ .Values.settings | toYaml | sha256sum }}
      labels:
        application: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
